import 'dart:html';

import 'package:flutter_app1/databases/sourcedb.dart';
import 'package:xml/xml.dart';

class OPMLParser{
  static List<RssSource> parseOPML(String input, {int startId = 0}){
    List<RssSource> result;
    XmlDocument.parse(input).findAllElements('outline').forEach((element) {
      if(element.getAttribute("type") == "rss"){
        result.add(new RssSource(
          id: startId++,
          name: element.getAttribute("text"),
          url: element.getAttribute("xmlUrl")
        ));
      }
    });
    return result;
  }

  static String generateOPML(List<RssSource> input){
    XmlBuilder builder;
    builder.processing('xml', 'version="1.0"');
    builder.element("opml", attributes: {"version": "2.0"},
      nest: () {
        builder.element("head", nest: () {
          builder.element("title", nest: "OPML generated by SbeamRSS");
          builder.element("dateCreated", nest: new DateTime.now().toString());
        });
        builder.element("body", nest: () {
          input.forEach((element) {
            builder.element("outline", attributes: {
              "text": element.name,
              "xmlUrl": element.url
            });
          });
        });
      }
    );
    return builder.buildDocument().toXmlString(pretty: true);
  }
}